;;;; Autogenerated ASD file for system "REMLIC.TEST"
;;;; In order to regenerate it, run update-asdf
;;;; from shell (see https://github.com/phoe-krk/asd-generator)
;;;; For those who do not have update-asdf,
;;;; run `ros install asd-generator` (if you have roswell installed)
;;;; There are also an interface available from lisp:
;;;; (asd-generator:regen &key im-sure)
(defsystem remlic.test
 :author "Masataro Asai"
 :mailto "guicho2.71828@gmail.com"
 :description "Test system of remlic"
 :license "LGPL"
 :depends-on (:remlic
              :fiveam
              :clml.data.r-datasets)
 :components ((:module "t"
               :components ((:file "0package")
                            (:file "1binary")
                            (:file "1multinomial"))))
 :perform (test-op :after (op c)
           (eval (read-from-string "(5am:run! :remlic)"))))
